name: Docker Image CI

on: [push]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: app
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  docker:
    name: Docker Login
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Push  
      - uses: opspresso/action-docker@v0.3.9
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/GitHub_Action:${{needs.tag.outputs.new_tag}}
