name: Docker Image CI

on: [push]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: app
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  docker:
    name: Login Docker
    needs: [tag]
    runs-on: ubunu-latest
    steps:
      - users: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitgubaction:latest
    - name: Image digest
      run:  echo ${{ steps.docker_build.outputs.digest }}
