name: Pull Request Builds
permissions:
  id-token: write
  contents: read
  actions: write
  checks: read
  packages: read
  pull-requests: write
  security-events: write
  statuses: write
on:
  push:
    branches: code
    
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: github/codeql-action/init@v2
      with:
        tools: https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.15.5/codeql-bundle.tar.gz
        languages: swift
